export const STORE = {
    currentSection: "notes",
    notes: [
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
      {
        id: uuidv4(),
        title: "A note",
        body: "A content",
        color: "white",
        deleted: false,
      },
    ],
  };